### ISSUE TITLE
Add groups functionality

### ISSUE THREAD

**Issue by evroon** [evroon/bracket#279]
In group stage, matches should be scheduled in separate groups that can come together in a subsequent stage.

**Comment by pekohub** [comment]
Hi Erik, I just installed the docker image, and it works flawlessly. The group stage would really be a cool thing to have. We regularly do 4 groups of 7 people in each group, like that everyone gets a guaranteed 6 matches, even if they don't advance to the knock-out single eliminiation phase.
For the advancement from group stage (round robin) to SE stage it will be good to be able to choose how many will advance (top 1, top 2, top 3).

**Comment by evroon** [comment]
@klikr I have implemented the group/pool functionality now, you can create multiple groups (with round robin format) and choose the top x from which group that will proceed to the next stage, which can be elimination or another group stage.
