### ISSUE TITLE
Feature request: Bulk Import players

### ISSUE THREAD

**Issue by klikr** [evroon/bracket#292]
To be able to add many players at once, a bulk import function is required. 
It would take a player per line, f.e. in csv style, with email addresses (if that's needed for later)
f.e.:

Jeff,Bridges,no.email@thank.you
Mark,Williams,less.email@thank.you

etc.

**Comment by evroon** [comment]
Yes this is indeed something that I planned to do, just a text field where you can paste csv content

**Comment by evroon** [comment]
You can now bulk insert players and teams, I am indeed considering a CSV like input for in the future (for now it would have no purpose indeed)
