### ISSUE TITLE
Why always localhost?

### ISSUE THREAD

**Issue by lordimac** [evroon/bracket#326]
Hello, why does the docker installation always trying to connect to localhost:8400? Its not running on localhost, its running behind a reverse proxy!

Error console when trying to login:
POST http://localhost:8400/token net::ERR_CONNECTION_REFUSED

**Comment by evroon** [comment]
The https://github.com/evroon/bracket/blob/master/docker-compose.yml file just forwards the ports from the containers to the host, so no reverse proxy is in place. It should just work.

If you want to change the address to which the frontend connects to the backend, you can change the environment variable `NEXT_PUBLIC_API_BASE_URL`:

https://github.com/evroon/bracket/blob/master/frontend/src/services/adapter.tsx#L25-L29

You can change that environment variable as written in [next.js docs](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables) or through the UI in Vercel if you use Vercel.

**Comment by evroon** [comment]
I have updated the docs now as well, see [#445 (comment)](https://github.com/evroon/bracket/discussions/445?converting=1#discussioncomment-8387940)
