### ISSUE TITLE
Add stage item failed

### ISSUE THREAD

**Issue by GithubPatrick91** [evroon/bracket#380]
Reproduce Error:

1. A fresh docker compose up
2. Add one Club
3. Create new Tournament
4. Add 4 Teams
5. Add Courts 
6. Add Stage (works)
7. Add stage item --> fails

```
Unhandled Runtime Error
Error: [@mantine/core] Option value must be a string, other data formats are not supported, got number
```

<details><summary>Error Output Details</summary>
<p>

Unhandled Runtime Error
Error: [@mantine/core] Option value must be a string, other data formats are not supported, got number

Call Stack
validateOptions
node_modules/@mantine/core/esm/components/Combobox/OptionsDropdown/validate-options.mjs (16:0)
OptionsDropdown
node_modules/@mantine/core/esm/components/Combobox/OptionsDropdown/OptionsDropdown.mjs (64:17)
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js (16305:0)
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js (20074:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (21587:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (4164:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (4213:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4277:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27451:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26434:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25738:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)

</p>
</details>

**Comment by GithubPatrick91** [comment]
thank you for your fast response. It would be nice to have a fix - i´m planning to use your great app for our tournament soon.

**Comment by evroon** [comment]
I haven't found any other issues, so I will close this
