### ISSUE TITLE
backend fails to start after version increase to 1.3.0

### ISSUE THREAD

**Issue by SoneNiko** [evroon/bracket#426]
![image](https://github.com/evroon/bracket/assets/36677468/187b0f22-21f1-4bba-a645-4a424aefd18c)

We have tried to start version 1.3.0 with a brand new empty database and it fails to create the data. We have since reverted back to 1.2.1 where this isn't the case and that works

**Comment by mathyvds** [comment]
Same issue here :)

**Comment by evroon** [comment]
Ah yes thanks for notifying me, I have a fix ready in #427 :)

**Comment by evroon** [comment]
Now it should work again in v1.3.1

https://github.com/evroon/bracket/releases/tag/v1.3.1

**Comment by SoneNiko** [comment]
also thank you for making this open source. I need this project very much ❤️
