### ISSUE TITLE
Question: reason for dev mode in production

### ISSUE THREAD

**Issue by SoneNiko** [evroon/bracket#481]
Your documentation seems to suggest that the environment needs to be set to "DEVELOPMENT" as per your docker compose file. If it can be avoided i would prefer to not do that in production. Is there a specific reason for that and if so can I still avoid that?

**Comment by evroon** [comment]
Ik not sure what you mean, the documentation page for running bracket in production doesn't mention any development environment:

https://docs.bracketapp.nl/docs/running-bracket/deployment

**Comment by evroon** [comment]
see also https://github.com/evroon/bracket/issues/441

**Comment by SoneNiko** [comment]
I am so sorry, I was really busy and I forgot that I already asked this question. sorry for wasting your time. keep up the amazing work

**Comment by evroon** [comment]
Ah no problem! Thanks :)
