### ISSUE TITLE
migrations are failing. This looks oddly like the other error

### ISSUE THREAD

**Issue by SoneNiko** [evroon/bracket#494]
#426 
![image](https://github.com/evroon/bracket/assets/36677468/113c1912-6ee1-492b-b59e-720077436dae)

**Comment by SoneNiko** [comment]
This kinda happened after both of these scenarios. I got around it by disabling the alembic migrations using the environment variable. This is just a temporary solution. I don't know what exactly is causing these issues with migration but since its probably going to happen again i will just open an issue again then.

To my limited understanding, the core issue seems to be that the migration is trying to create an pgsql enum type which already exists which is what happens last time. maybe its just an issue with how alembic handles migrations for enum types.

**Comment by robigan** [comment]
@SoneNiko You can close this now. Migrations were manually made using alembic stamp version in prod. Internal for us: See incident report 002 for steps taken.
