### ISSUE TITLE
Implement logout button

### ISSUE THREAD

**Issue by robigan** [evroon/bracket#513]
The logout button only brings the user to the profile edit page. Without any logging out functionality working.

**Comment by evroon** [comment]
Ah yeah I added it as a placeholder but never got around to actually implementing the logout logic.

**Comment by robigan** [comment]
Then in that case, ye olde delete site cookies will do xD

**Comment by evroon** [comment]
Haha yes indeed, but note the JWT is stored in localstorage, no cookies involved :)

**Comment by robigan** [comment]
Yeah, I'm aware but firefox has the one button that is called "Clear cookies and site data..."
