### ISSUE TITLE
Teams logos

### ISSUE THREAD

**Issue by robigan** [evroon/bracket#515]
Allow teams to have team logos. I'd do this myself, but I don't know how to use Alembic 😅

**Comment by evroon** [comment]
Cool! I could do the alembic part if you want

**Comment by robigan** [comment]
Well I may as well learn how to do it, I just don't know how to.

**Comment by robigan** [comment]
I don't mind working with Python, but I can do frontend part if you wish to do backend

**Comment by evroon** [comment]
If you don't mind doing the backend, then go ahead :)
I think the alembic part is quite easy though, you first change the [schema](https://github.com/evroon/bracket/blob/master/backend/bracket/schema.py) (probably just adding one column)
And then you just run:

	pipenv run alembic revision --autogenerate -m "Adding teams.logo_paths"
