### ISSUE TITLE
Error when trying to add a round to a Swiss tournament

### ISSUE THREAD

**Issue by avsilva** [evroon/bracket#577]
When I click the button "Add Round" on a Swiss tournament I get the following error:

Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by robigan** [comment]
Well what's the browser console error?

**Comment by avsilva** [comment]
The console error is:  `TypeError: upcoming_match.elo_diff.toFixed is not a function`
on line src/components/tables/upcoming_matches.tsx (63:5). more precisely on 
`<td>{upcoming_match.elo_diff.toFixed(0)}</td>`

The elo_diff value is a string so toFixed cannot be applied. If I change to `Number(upcoming_match.elo_diff).toFixed(0)` the problem is solved. Can you confirm?

**Comment by evroon** [comment]
You're right, I fixed this in: https://github.com/evroon/bracket/pull/687
If it still happens, please reopen this
