### ISSUE TITLE
Display result of a round robin round

### ISSUE THREAD

**Issue by TilmanJimenez** [evroon/bracket#683]
Hopefully I didn't just miss this while trying the demo!

While the standings in single elimination are quite clear, it would be nice to have an overview of the standings in a round robin pool:
Something like

| Team | Points | Diff |
| ------------- | ------------- |------------ |
| Team 1 | 4 | +3 |
| Team 2 | 2 | +2 |
| Team 3 | 2 | -2 |
| Team 4 | 0 | -3 |

Given that the information is calculated, displaying should be easy

Also thanks for this project!

**Comment by evroon** [comment]
This can probably be improved, but the functionality does exist although a bit hidden perhaps.

In the overview of teams, you can filter on stage items, and select a round robin stage item.

Do you have a specific idea on how to make the user experience better?

**Comment by TilmanJimenez** [comment]
Ah I see!
Well I'm now certain that I would never have found it 😄
I think at least for my use case it would be interesting to have it in the dashboard between the stages (our tournament follows soccer cups, group stages followed by single elimination). That way teams could look up their standings and know if they have a shot at being first in their group (or second) and what the other groups are doing. That is whom they'll be facing in the elimination round.

**Comment by evroon** [comment]
This is now fixed, the dashboard shows standings per stage item (including round robin)
