### ISSUE TITLE
Internal Server Error - Debain 12

### ISSUE THREAD

**Issue by mcm2007** [evroon/bracket#779]
Hey everyone! I saw this project and decided to give it a try.
Howver as you can see above after following the quickstart guide on a EC2 Debain instance i get the error Internal Server Error.
I already tried to change to production, set the ip address instead of localhost but when i login i can olny see Internal Server Error.
Here is what the inspector says: 
![image](https://github.com/evroon/bracket/assets/60483484/18b266ef-f34a-4c3a-90b9-ad74e7ac9b21)
Will wait for some updates!

**Comment by djpiper28** [comment]
Hi there, not the main dev. I think this may be related to CORS. The python library that accepts connections has an environment argument for a Cors regex. What is your config?

**Comment by evroon** [comment]
Yes CORS is becoming a common problem, I think I'll disable the entire middleware by default. Now it's enabled by default

**Comment by mcm2007** [comment]
So i decided to re-start and will be going on a fresh debain installation;
Done sudo apt-get install docker-compose;
Pulled the repo with git clone https://github.com/evroon/bracket.git
Now in the docker-compose.yml:
version: '3.1'

services:
    bracket-frontend:
        image: ghcr.io/evroon/bracket-frontend
        container_name: bracket-frontend
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_BASE_URL: "http://tornuments.byteb.shop:8400"
            NEXT_PUBLIC_HCAPTCHA_SITE_KEY: "my hcathpa key"  # Public test key
        restart: unless-stopped

    bracket-backend:
        image: ghcr.io/evroon/bracket-backend
        container_name: bracket-backend
        ports:
            - "8400:8400"
        environment:
            ENVIRONMENT: "DEVELOPMENT"
            PG_DSN: "postgresql://bracket_dev:bracket_dev@postgres:5432/bracket_dev"
        volumes:
            - ./backend/static:/app/static
        restart: unless-stopped
        depends_on:
          - postgres

    postgres:
        image: postgres
        restart: always
        environment:
          POSTGRES_DB: bracket_dev
          POSTGRES_USER: bracket_dev
          POSTGRES_PASSWORD: bracket_dev

Then done sudo docker-compose up -d
Opened ports 3000 and 8400 (just in case) TCP on AWS.
You can try and access it on http://tornuments.byteb.shop:3000
But cant login somehow...

**Comment by mcm2007** [comment]
Update: Somehow, idk what on god happend but it worked.
Issue: An warning appears when any user wants to create an account; and it is suppost to be visible to everyone the join tornument part... How can i do that?
Also https? How is it managed?
Thanks for the help so far!
