### ISSUE TITLE
Error: There is no draft round, so no matches can be scheduled.

### ISSUE THREAD

**Issue by SwedishChef** [evroon/bracket#828]
V1.5.0

- Swiss stage / add round  (first round has scheduled matches)
- 1st round gets solid border / 2nd round is empty with dashed border
- Note below rounds is still "Schedule new matches for Round 01 in Stage" (should be ... Round 02?)
- instead of a list of matches error is shown "There is no draft round, so no matches can be scheduled."

- configured: 1 club, 1 tournament with 10 teams

I tried several times, the error occurs every time I try to add a round.

**Comment by evroon** [comment]
Thanks! Ah yes I came across this as well, I fixed it now in #903 
But there's still some work to be done to make the swiss system more user-friendly
