### ISSUE TITLE
Configuration option to disable captchas completely

### ISSUE THREAD

**Issue by Rinma** [evroon/bracket#867]
Hi,

Currently, I am trying to host a Bracket instance with docker compose on my server. 
Now I got the following problem that I really dislike the solution from hCaptcha, they have one of the worst captchas I have ever seen, they mostly don't make sense or don't work at all, and it is like they get worse every month.

Now I want to have a configuration option to disable captcha completely, I don't want to use it at all on my self-hosted instance.

The problem is, when I set `NEXT_PUBLIC_HCAPTCHA_SITE_KEY` to an empty string, the frontend container is crashing with this loop showing in the logs

```
# Define an array of environment variable names
env_vars=("NEXT_PUBLIC_API_BASE_URL" "NEXT_PUBLIC_HCAPTCHA_SITE_KEY")
Checking that we have variables...
echo "Checking that we have variables..."
# Iterate over the array and perform checks
for var in "${env_vars[@]}"; do
  test -n "${!var}"
done
```

And if I set `NEXT_PUBLIC_HCAPTCHA_SITE_KEY` to a random value, the registration is not possible because the captcha can't be solved.

**Comment by evroon** [comment]
That's indeed a bug. https://github.com/evroon/bracket/pull/878 should fix this, could you try this again on the lastest master?
