### ISSUE TITLE
Swiss tournament round bug

### ISSUE THREAD

**Issue by Nikvothe** [evroon/bracket#948]
Hi, there seems to be a bug in the addition of another round for a Swiss tournament. This bug does not show up in the demo [](https://www.bracketapp.nl/login)

I created 8 players for 8 teams (each team has 1 player), perhaps this setup is wrong?

I'll share a screenshot:
![localhost_3000_tournaments_1_swiss_1 (1)](https://github.com/user-attachments/assets/0a46b584-ce49-4cc5-92ec-805228912f7f)

For context, I'm setting up a local Dragon Ball Sparking Zero tournament, there's only one big monitor, pc and 2 controllers, meaning we've only one "court".  I suspect we'll be around 8 people so the Swiss tournament structure would allow us to finish a tournament in 4/5 rounds and reduce the chance of somebody winning all the time. The idea is to have many of these sequences/tournaments throughout the day, so that we can distribute symbolic trophies to the winners.

**Comment by evroon** [comment]
Thanks, I think I solved this in https://github.com/evroon/bracket/pull/909 which would be merged soon, but I'll check it it's really fixed
